title: Kai Qin TAN (Duncan)

description: Welcome! 欢迎！Selamat Datang! ようこそ！ 
show_downloads: False
# theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
